bundle:
  name: turbine-pipeline
targets:
  dev:
    workspace:
      host: https://<instanceurl>.databricks.com
    default: true
resources:
  jobs:
    turbine-job:
      name: turbine-job
      tasks:
        - task_key: run-pipeline
          notebook_path: /Workspace/notebooks/pipeline_notebook.py
          existing_cluster_id: <your-cluster-id>
      schedule:
        quartz_cron_expression: "0 0 * * * ?"
        timezone_id: UTC
